"""Replay-buffer skeleton for alpha_zero."""


class ReplayBuffer:
    """Stores self-play examples for AlphaZero training."""

    def __init__(self, capacity: int):
        """Initialize a fixed-capacity replay buffer.

        Args:
            capacity: Maximum number of examples to retain.

        Returns:
            None.

        The buffer should eventually hold states, MCTS policy targets, and
        game-outcome value targets generated by self-play.
        """
        raise NotImplementedError("Implement replay buffer initialization.")

    def add(self, state, policy_target, value_target) -> None:
        """Add one self-play training example.

        Args:
            state: Environment observation or encoded state.
            policy_target: Search-improved action distribution.
            value_target: Final game outcome from the current player's view.

        Returns:
            None.

        Each row teaches the network to imitate MCTS policy and predict game
        outcome.
        """
        raise NotImplementedError("Implement replay insertion.")

    def sample(self, batch_size: int):
        """Sample a training batch from replay.

        Args:
            batch_size: Number of examples to sample.

        Returns:
            Batch of states, policy targets, and value targets.

        Sampling connects self-play data collection to neural-network updates.
        """
        raise NotImplementedError("Implement replay sampling.")
